---

apiVersion: v1
kind: Namespace

metadata:
  name: nwdb
  labels:
    name: nwdb
    version: v1

---

apiVersion: v1
kind: Secret

metadata:
  name: nwdb-secret
  namespace: nwdb

data:
  db_password: changeit

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwdb-deploy
  labels:
    name: nwdb-pod
    version: v1

spec:
   replicas: 1
   minReadySeconds: 30
   selector:
      matchLabels:
        name: nwdb-pod
        version: v1
   template:
      metadata:
        name: nwdb-pod
        labels:
            name: nwdb-pod
            version: v1
      spec:
         containers:
          - name: nwdb-container
            image: stackupiss/northwind-db:v1
            imagePullPolicy: IfNotPresent
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: nwdb-secret
                    key: db-password
            ports:
              - name: mysql-ports
                containerPort: 3306

---


